### ISSUE TITLE
Splunk home directory creation issue

### ISSUE THREAD

**Issue by NinjaSl0th** [aplura/Tango#16]
When running initial setup from instructions on what would be the sensor, the directory /home/splunk doesn't get created and kept causing my install to fail. *edit*Manually creating /home/splunk [before running setup scripts], everything works fine. 

Perhaps this was just something wrong with 14.04.2 LTS?

**Comment by brianwarehime** [comment]
This should be fixed now, I'm manually creating the home directory in the script. I think in order for the home directory to show up before, you would need to log out and log back in, so, that's not really efficient in the script, so this should take care of that. If you run it again on another box, let me know if it's still broke.
