### ISSUE TITLE
Tango App Not Processing Data

### ISSUE THREAD

**Issue by mackwage** [aplura/Tango#19]
Sorry if this is more of a Splunk issue but wanted to start here. :)

I have my sensors setup and logging back to Tango within splunk. In Tango, I can see my sensors within Sensor Mgmt. If I go to Splunk Search and Reporting, I can see the kippojson logs.

However, when navigating through the dashboards, I get no results found.

![homepg](https://cloud.githubusercontent.com/assets/454938/8678244/5e7eee5c-2a08-11e5-8e7a-baea843d5841.PNG)

When I see the logs, most of them are logon attempts but when I go to the username/password analysis page, I get no results there as well.

![logons](https://cloud.githubusercontent.com/assets/454938/8678264/6ff0f4f0-2a08-11e5-9601-5d73ab683309.PNG)

I followed the server instructions on the main page; Tango is added to the default search index for my user.

**Comment by brianwarehime** [comment]
Would you be able to message me on google chat? I think troubleshooting might go a little faster that way. brianwarehime@gmail.com

Thanks!

**Comment by mackwage** [comment]
Sure thing! Just did. thank you much!

**Comment by mackwage** [comment]
This was resolved! Kippo was using a new format of json which isn't yet supported by Tango. Reverted back to old version and updated inputs.conf for the forwarder and all is well. @brianwarehime also updated the repo so it would revert back to older version for future installs.
