### ISSUE TITLE
issues with micheloosterhof/kippo

### ISSUE THREAD

**Issue by rezuma** [aplura/Tango#22]
There is an issue with the Kippo sensor.sh pulls down. 
micheloosterhof/kippo
https://github.com/micheloosterhof/kippo/issues/35

Thanks

Rezuma

**Comment by mackwage** [comment]
Looks like his version of Kippo was pulled. :(

**Comment by rezuma** [comment]
They have moved the development to https://github.com/cowrie/cowrie

The issues was related to an import statement IPluggableAuthenticationModules and I don think it has been fixed in cowrie neither

from twisted.cred.credentials import IUsernamePassword, ISSHPrivateKey, \
    IPluggableAuthenticationModules, ICredentials


Rezuma

**Comment by brianwarehime** [comment]
I need to move over to cowrie support for this, hopefully the Twisted issue will be fixed soon as well.

**Comment by brianwarehime** [comment]
Hey guys, I went ahead and changed everything over to use Cowrie. Please let me know if you notice any issues with using the sensor.sh script or the Tango Splunk app. Thanks!
