### ISSUE TITLE
Kippo Version Issues

### ISSUE THREAD

**Issue by davidroush** [aplura/Tango#24]
Hello, I'm having issues getting Tango to run (and unfortunately I lost my good install). You mention Michel Oosterhof's fork is necessary, however he has renamed his project "cowrie". After fixing the download link I can't get cowrie to run (even after replacing "cowrie" with "kippo", hoping that's all that changed). Can someone either hook me up with the last working version of Kippo or tell me how to fix the cowrie installations?

**Comment by brianwarehime** [comment]
Hey David, working on fixing the issue and replacing Kippo with Cowrie. Hopefully have it working again this week. I'll update this issue once I get it working again. Sorry for the trouble

**Comment by davidroush** [comment]
No trouble at all, thank you very much for the support. Awesome project by the way, looking forward to having it back up and running!

**Comment by brianwarehime** [comment]
Hey David, this issue should be fixed now. I changed everything over to use Cowrie by default. If you end up testing the new sensor.sh script, please let me know if you see any errors with the script or using the Splunk app. Thanks!

**Comment by davidroush** [comment]
Worked perfectly, thank you for the assistance. Again, great project and thank you for the support. Send me to a "donate" button and I'll gladly buy you a beer!
